# Generated by Django 5.2.1 on 2025-06-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pul_berish',
            name='status',
            field=models.CharField(choices=[('keyinroq_tolanadi', "Belgilangan sanada to'lanadi"), ('joyida_tolandi', "Joyida to'landi"), ('bolib_tolanadi', "Bo'lib to'lanadi")], default='joyida_tolandi', max_length=25),
        ),
    ]
