# Generated by Django 5.2.1 on 2025-06-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pul_berish_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pul_olish',
            name='status',
            field=models.CharField(choices=[('tolangan', "To'langan"), ('tolanmagan', "To'lanmagan")], default='tolanmagan', max_length=25),
        ),
        migrations.AddField(
            model_name='pul_olish',
            name='tolangan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
