# Generated by Django 5.2.1 on 2025-06-05 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pul_olish_sabab_alter_pul_olish_tolangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_add_expanse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_add_expanse_to_others',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_add_new_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='can_change_expanse',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Harajatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabab', models.CharField(blank=True, max_length=300, null=True)),
                ('summa', models.DecimalField(decimal_places=2, max_digits=30)),
                ('sana', models.DateField(auto_now_add=True)),
                ('ishchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expanses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
