# Generated by Django 5.2.1 on 2025-06-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_can_add_expanse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_show_harajatlar',
            field=models.BooleanField(default=False),
        ),
    ]
