# Generated by Django 5.2.1 on 2025-06-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customuser_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harajatlar',
            name='sana',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pul_berish',
            name='sana',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pul_olish',
            name='sana',
            field=models.DateField(),
        ),
    ]
