# Generated by Django 5.2.1 on 2025-06-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_harajatlar_sana_alter_pul_berish_sana_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pul_berish',
            name='status',
        ),
        migrations.AddField(
            model_name='pul_berish',
            name='berildi',
            field=models.BooleanField(default=False),
        ),
    ]
