# Generated by Django 5.2.1 on 2025-06-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_pul_berish_status_pul_berish_berildi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pul_berish',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', max_length=3),
        ),
        migrations.AddField(
            model_name='pul_olish',
            name='currency',
            field=models.CharField(choices=[('UZS', 'UZS'), ('USD', 'USD')], default='UZS', max_length=3),
        ),
    ]
