# Generated by Django 5.2.1 on 2025-07-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_pul_berish_currency_pul_olish_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='harajatlar',
            options={'verbose_name': 'Harajat', 'verbose_name_plural': 'Harajatlar'},
        ),
        migrations.AlterModelOptions(
            name='pul_berish',
            options={'verbose_name': "Qarz to'lash", 'verbose_name_plural': "Qarz to'lash"},
        ),
        migrations.AlterModelOptions(
            name='pul_olish',
            options={'verbose_name': 'Qarz olish', 'verbose_name_plural': 'Qarz olish'},
        ),
        migrations.AlterModelOptions(
            name='taminotchi',
            options={'verbose_name': 'Yetqazib beruvchi', 'verbose_name_plural': 'Yetqazib beruvchilar'},
        ),
        migrations.AddField(
            model_name='pul_berish',
            name='dollar_amount2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pul_olish',
            name='dollar_amount',
            field=models.FloatField(default=0),
        ),
    ]
