# Generated by Django 5.2.1 on 2025-07-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_pul_berish_currency_pul_olish_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='harajatlar',
            options={'verbose_name': 'Harajat', 'verbose_name_plural': 'Harajatlar'},
        ),
        migrations.AlterModelOptions(
            name='pul_berish',
            options={'verbose_name': "Qarz to'lash", 'verbose_name_plural': "Qarz to'lash"},
        ),
        migrations.AlterModelOptions(
            name='pul_olish',
            options={'verbose_name': 'Qarz olish', 'verbose_name_plural': 'Qarz olish'},
        ),
        migrations.AlterModelOptions(
            name='taminotchi',
            options={'verbose_name': 'Yetqazib beruvchi', 'verbose_name_plural': 'Yetqazib beruvchilar'},
        ),
        migrations.AddField(
            model_name='pul_berish',
            name='dollar_amount2',
            field=models.DecimalField(decimal_places=2, default=12700, max_digits=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pul_olish',
            name='dollar_amount',
            field=models.DecimalField(decimal_places=2, default=12700, max_digits=30),
            preserve_default=False,
        ),
    ]
