# Generated by Django 5.2.1 on 2025-07-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_customuser_options_alter_harajatlar_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pul_berish',
            name='dollar_amount2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='pul_olish',
            name='dollar_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
    ]
